name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNETVERSION: "8.0.x"
  APP: "I8Beef.CodeAnalysis.EditorConfig"
  CSPROJ: "I8Beef.CodeAnalysis.EditorConfig.csproj"
  PACKOUTPUTPATH: "./out"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}

      - name: Get version
        id: version
        run: echo "version-without-v=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get previous release tag
        id: previousTag
        run: |
          PREV_REV=$(git rev-list --tags --max-count=1 --skip=1 --no-walk)
          PREV_TAG=$(git describe --tags ${PREV_REV})
          echo "tag=${PREV_TAG}" >> $GITHUB_OUTPUT

      - name: Build
        run: dotnet pack ${{ env.CSPROJ }} -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -o ${{ env.PACKOUTPUTPATH }}

      - name: Upload NuGet build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP }} NuGet Packages
          path: ${{ env.PACKOUTPUTPATH }}

      - name: MyGet push
        run: dotnet nuget push "${{ env.PACKOUTPUTPATH }}/*.nupkg" --source https://www.myget.org/F/i8beef/api/v3/index.json --api-key ${{ secrets.MYGET_TOKEN }} --skip-duplicate --no-symbols true

      - name: GitHub NuGet push
        run: dotnet nuget push "${{ env.PACKOUTPUTPATH }}/*.nupkg" --source https://nuget.pkg.github.com/i8beef/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols true